### ISSUE TITLE
Check did not write to STDOUT. (debian 10 buster)

### ISSUE THREAD

**Issue by dhpowrhost** [sensu/monitoring-plugins#12]
The checks (at least both ssh and http) fails on agent with exit code 4294967295 when running on debian buster. stretch has no issues.
![image](https://user-images.githubusercontent.com/11715805/74133730-7e7ff680-4be9-11ea-95e6-eb1c3d68eb51.png)

No issues when running the check by hand.

**Comment by toozej** [comment]
My pull request #10 will compile assets for Debian 10 Buster
