### ISSUE TITLE
SHA512 sums wrong for 2.5.1 release in asset definition

### ISSUE THREAD

**Issue by pfak** [sensu/monitoring-plugins#19]
At very least the following assets do not match what is in the bonsai asset definition:

https://assets.bonsai.sensu.io/a162acecf701065795231c8194785f2edd292dd3/monitoring-plugins-ubuntu1604_2.5.1_linux_amd64.tar.gz

Definition: `25e37b15846872243b95ca6ea42a56cf8105016425e751280d5f4d75719935655ec5ff03cc0d917d19a00a6290e9d59e424669ebad0f811715fe78e7c116d431`
File: `f88a0b46b1c462851d9feea4cd177b6892fcc0ba2d69c85584745787938092ecbc285e4cd40c9ff7180610d2b136fccf5ff6bbb88d0c4f2c350893156160336e`

https://assets.bonsai.sensu.io/a162acecf701065795231c8194785f2edd292dd3/monitoring-plugins-debian10_2.5.1_linux_amd64.tar.gz

Definition: `9bfd52f88e5755aaa095864141f934534504d952f85b82bf0d867ba7878d3622ac2f7f110a471b2832b7be0e9703781de2a81aa54fef8c670aa8a7d3c0f01955`
File: `35bce33008c623eb844222d1e7cc315b69ab8e54fa64d0221f251e2ec095fd75a3f8673fa988dc33870d957b5d067cd7a167b86e0d3a8149143a16bd6cbdec33`

https://assets.bonsai.sensu.io/a162acecf701065795231c8194785f2edd292dd3/monitoring-plugins-ubuntu1804_2.5.1_linux_amd64.tar.gz

Definition: `bb64a5a78cc0d08f73e5aa0a373d30762f5a3a665f3c34a8ce174a874a3da23c773ef9c452b5b4e195a983246be13c909a9abc1a5c8680d0ab1ecbf80cccfd69`
File: `d3ef8dc3cc76d58993148a2107dbcfd5a290badaf770d9177ac6c81d1f4f6a5d6a4f3489121969e5f0d16799e21481f83ba5febb9c360c82379b51959890fd73`

**Comment by jspaleta** [comment]
I cannot confirm this observation.
Here is what I just did locally on my fedora workstation checking the ubuntu1804 build for release 2.5.1

```
$ wget https://assets.bonsai.sensu.io/a162acecf701065795231c8194785f2edd292dd3/monitoring-plugins-ubuntu1804_2.5.1_linux_amd64.tar.gz
$ sha512sum monitoring-plugins-ubuntu1804_2.5.1_linux_amd64.tar.gz 
bb64a5a78cc0d08f73e5aa0a373d30762f5a3a665f3c34a8ce174a874a3da23c773ef9c452b5b4e195a983246be13c909a9abc1a5c8680d0ab1ecbf80cccfd69  monitoring-plugins-ubuntu1804_2.5.1_linux_amd64.tar.gz
```

The `bb64...fd69` matched what bonsai lists and also matches what the github 2.5.1 release checksum file lists for `monitoring-plugins-ubuntu1804_2.5.1_linux_amd64.tar.gz`


If you are getting checksum mismatches, you may have an http proxy or a disk space problem causing the file you download to not be what is expected.

**Comment by pfak** [comment]
This is a two year old issue. It was confirmed at the time on the Sensu slack, I was asked to report it (by you, if memory serves). I assume this has been long since rectified.

And no, I did not have a proxy MITMing TLS HTTP connections.

**Comment by jspaleta** [comment]
Oops old issue. Looks like its working now so  I guess its closable.
