### ISSUE TITLE
debian asset artifact seg-faulting in ubuntu

### ISSUE THREAD

**Issue by ptpford** [sensu/monitoring-plugins#2]
Including the debian asset as a runtime-asset, even if nothing in the package is directly invoked, results in a crash in the check and an unknown result.

Trial and error reveals this is due to segmentation faults when the LD_LIBRARY_PATH is set to the asset's libdir, and removing the libc.so.6 fixes the issue.

Tested on: Ubuntu 18.04 LTS (desktop) and the latest Ubuntu container from docker.io

**Comment by ptpford** [comment]
I thought my testing showed just removing libc was enough; but it was just enough to stop the seg faults.  Unfortunately it has a ripple effect since other libs depend on it.  So far, just wiping the lib directory is working on my small set of clients.

**Comment by sjthespian** [comment]
I can confirm that I'm seeing the same thing in 18.04. It works fine on my 16.04 system, but not on 18.04.

**Comment by jspaleta** [comment]
Coming back to this.

Anyone running Ubuntu systems interesting in testing Ubuntu specific builds?

We introduced multi-build support in Bonsai and Bonsai integration in sensuctl, so its much MUCH easier to deal with target specific builds from a user standpoint.

We can now safely spin up Ubuntu specific builds and then try to sort out a debian 'family' build that works on both debian and ubuntu.
