### ISSUE TITLE
The http-check plugin should support checking HTTP responses for strings

### ISSUE THREAD

**Issue by mgibson323** [sensu/monitoring-plugins#26]
The http-check plugin from the [Monitoring Plugins](https://bonsai.sensu.io/assets/sensu/monitoring-plugins) asset should be able to check an HTTP response for strings, so it can be used to check health and other similar statuses.

## Background
There is a Sensu Docs article on [how to monitor Sensu with Sensu](https://docs.sensu.io/sensu-go/latest/operations/monitor-sensu/monitor-sensu-with-sensu/) that includes examples of how to monitor an external etcd cluster for health. Using the http-check from the [Monitoring Plugins](https://bonsai.sensu.io/assets/sensu/monitoring-plugins) asset always returns a 200 regardless of whether the cluster is healthy or not - so adding a way to check the response for `"health": "false"` or `"health": "true"` would be a big improvement. 

## Feature Suggestion

Add a way for the http-check plugin to check HTTP responses for strings so it can be used for health checks.

**Comment by asachs01** [comment]
This feel like it's outside of the scope of this project, as the project just compiles plugins from an external source well outside of Sensu's control. I'm going to close this out, unless @jspaleta or @calebhailey feel differently.
