### ISSUE TITLE
Feature Request: Assets for EL 9

### ISSUE THREAD

**Issue by pstadt** [sensu/monitoring-plugins#41]
RHEL9 / AlmaLinux 9 / RockyLinux 9 are in the world for nearly a year now.
Would be great to have checks running without any hacks.

**Comment by hfinucane** [comment]
I've been going through old sensu official repos and poking them to see if they worked on EL9, and stopped checking issues/PRs, missed #40, and wrote my own slightly different PR- #42.

But yeah, EL9 support sounds like a good idea.

**Comment by echlebek** [comment]
Rocky 9 is available in the latest release, closing
